// <auto-generated />
using System;
using EngineerFlow.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EngineerFlow.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401081330_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("EngineerFlow.API.Models.CompletionEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionSummary")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobRequestId")
                        .IsUnique();

                    b.ToTable("CompletionEvents");
                });

            modelBuilder.Entity("EngineerFlow.API.Models.JobRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequesterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JobRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedTo = "Bob Smith",
                            Category = "DevOps",
                            CreatedAt = new DateTime(2024, 12, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The main branch pipeline has been failing since the last merge. Investigate and resolve.",
                            Priority = 3,
                            RequesterName = "Alice Chen",
                            Status = 1,
                            Title = "Fix CI/CD pipeline failure",
                            UpdatedAt = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Category = "Backend",
                            CreatedAt = new DateTime(2024, 12, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Add rate limiting middleware to the public API endpoints to prevent abuse.",
                            Priority = 2,
                            RequesterName = "Carlos Rivera",
                            Status = 0,
                            Title = "API rate limiting implementation",
                            UpdatedAt = new DateTime(2024, 12, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AssignedTo = "Eve Johnson",
                            Category = "Database",
                            CreatedAt = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Slow queries on the reports page — profile and add appropriate indexes.",
                            Priority = 1,
                            RequesterName = "Dana Patel",
                            Status = 0,
                            Title = "Database index optimisation",
                            UpdatedAt = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EngineerFlow.API.Models.CompletionEvent", b =>
                {
                    b.HasOne("EngineerFlow.API.Models.JobRequest", "JobRequest")
                        .WithOne("CompletionEvent")
                        .HasForeignKey("EngineerFlow.API.Models.CompletionEvent", "JobRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRequest");
                });

            modelBuilder.Entity("EngineerFlow.API.Models.JobRequest", b =>
                {
                    b.Navigation("CompletionEvent");
                });
#pragma warning restore 612, 618
        }
    }
}
